#!/usr/bin/env python3
"""
Update speaker bios in conference.json from the provided text
"""

import json

# Speaker bios from Sessionize
speaker_bios = {
    "Uwe Ricken": "Uwe Ricken is working with IT systems since the 90's. The start of experiences with Microsoft SQL Server came with the assignment for development of membership administration software for the American Chamber of Commerce in Germany. The software has been distributed to five additional European countries. The primary passion for developments with Microsoft SQL Server expanded in 2007 with his engagement as a DBA for Deutsche Bank AG in Frankfurt am Main. After 6 years of operational experiences as a DBA and over 14 years as a developer of complex database models he achieved the \"Microsoft Certified Master – SQL Server 2008\" certification which \"was\" the highest technical certification. The year 2013 finished with the first MVP award for his support to the Microsoft SQL Server community in Germany and Europe. To provide his deep knowledge about Microsoft SQL Server to the interested community Uwe Ricken is blogging since 2010 at http://www.sqlmaster.de about his daily experiences with Microsoft SQL Server. His blog posts are in German language only to provide the German speaking SQL community inside views into the technology of Microsoft SQL Server. Uwe Ricken is a speaker on many international conferences and events and preferred topics are \"Database Internals\", \"Indexing\" and \"Development\".",

    "Paula García Esteban": "Freelance: data visualization and AI training. IA/ML Instructor @ LinkedIn Learning. #PBICoreVisuals Community Representative. Top LinkedIn Data Visualization Voice. Microsoft MVP Data Platform & AI Platform. I trust the power of data and persuasive communication.",

    "Abhinav Jayanty": "I'm a Data Engineer and data analytics enthusiast experienced in working with the Azure data platform and Microsoft Fabric. With multiple Azure and Fabric certifications, I'm passionate about sharing knowledge and love presenting on topics like Kusto, Fabric and how they work with the wider Azure ecosystem. I'm also a part of Redgate's Community Ambassadors programme, helping Redgate to support data community events around the world through speaking and content creation. Outside of data, I'm an avid fan of football and Formula 1, and I enjoy cooking, whisky, and making plans to travel the world.",

    "Marc Lelijveld": "Data Platform MVP, Power BI and Fabric enthusiastic, public speaker and passionate for everything which transforms data into action! Working at Macaw in the Netherlands as Solution Architect and Technical Evangelist in the Data Solutions & Insights team. What I like the most? Sharing my thoughts, experience, best-practices and enthusiasm about Microsoft data platform with others. I mostly do this in public speaking at usergroups, conferences, customer presentations and end-user training. Besides that I also have my own blog which you can find at https://data-marc.com/",

    "Brian Bønk": "Brian has worked with data and analytics for more than two decades - varying projects on both size and complexity. Now, by combining deep experience with a human approach to data and analytics, and a deep understanding of platform implementations, Brian build solutions that deliver actual change for people, for business, for everyone. Brian is a Data Platform MVP and Microsoft Recognized Fasttrack Solution Architect. Brian loves data and is always trying to glue the business and tech together using his knowledge and experience. He is always open to meet new people and help them to get better tomorrow.",

    "Geir Alstad": "DadOps and T-SQL geek living in Oslo. I am passionate about democratising data and analysis. I am working towards native cloud residency in Azure.",

    "Olivier Van Steenlandt": "Olivier Van Steenlandt is a Business Intelligence Professional who spent most of his early career assisting retail companies to get more value of their data using the Microsoft BI Stack (SSIS, SSAS, SSRS, Power BI). As his first experience in the field (in Business Intelligence), Olivier worked as a Big Data Analyst using tools such as Hadoop and Spark. In 2015 the focus changed to traditional data warehousing & reporting using SSIS, SSRS & MicroStrategy. A bit later, around June 2019, the opportunity arose to fill the position of BI Teamlead. In this function he was able to set up a hybrid BI Team (team members in Belgium and Belarus). Early 2020, Olivier joined the dataMinds crew as a core member, assisting to organise several events. Around April 2021, Olivier started a new position as BI Teamlead in another Retail Company to support business growth. Besides the challenge to help the BI Team grow and deliver projects on time, he started to use SSAS & Power BI. In April 2025, Olivier stepped away from internal positions and became an independent consultant. When Olivier is not working there is a high chance that you find him on a football field, studying (BI Related), playing music (Saxophone / Piano) or cooking.",

    "Bas Land": "Bas is co-founder of Kimura Data Intelligence. He works as a data architect and specialises in Microsoft Fabric. He speaks and blogs about these experiences to share knowledge with the community and holds a Dataplatform MVP title. He is an experienced data engineer and architect with over 10 years of experience in Microsoft SQL Server, Azure and now Fabric technology implementations. In his spare time he likes to practice sports (Brazilian jiu-jitsu, running, weight lifting) and also traveling with his wife & son, and their three-year-old dachshund (daxhund?) Chester.",

    "Juliana Smith": "Juliana Smith is a multi-award-winning IT Chartered Professional with over 15 years in tech. Since 2020 she specialised in Power BI and UI design, transforming complex project data into clear, accessible and actionable insights. Through her blog Smart Frames and YouTube channel @AccessibleBI, Juliana shares valuable insights on developing more inclusive designs. By breaking down complex concepts into practical strategies, she makes data accessibility achievable for everyone, empowering individuals and organisations to create equitable, data-driven solutions.",

    "Oliver Engels": "Oliver Engels is CEO of oh22data AG, a Microsoft Gold Partner in Germany specialized in CRM and BI. His interests are on Azure, Data Governance and Integration, Machine Learning and Visualization Tools like SSRS, Power BI and Tableau. Oliver has worked with SQL Server since version 6.5 and is a founding member and current president of German Microsoft Data Platform Community (PASS), a PASS Regional Mentor, and runs the Frankfurt PASS Chapter. Since 2012 he is a Microsoft Data Platform MVP and a also worked as a Microsoft pTSP. If he is not working with data, he loves working with his Golden Retrievers and supports a charity project training dogs for disabled children. OK, he is an enthusiastic Land Rover Defender driver as well.",

    "Hugo Kornelis": "Hugo Kornelis is an established SQL Server community expert who spends a lot of time at various conferences. He is also a blogger, technical editor of a variety of books, and Pluralsight author. He was awarded SQL Server MVP and Data Platform MVP 17 times (2006 - 2016 / 2019 - now). When not working for the community, he is busy at his day job: freelance database developer/consultant. Hugo has over 25 years of SQL Server experience in various roles. Starting from a strong database design background, he has spent the last ten years specializing in execution plans and query performance tuning.",

    "Zita Pelok": "Enthusiastic People Analytics professional and organizational sociologist with over 10 years of experience in HR and 5 years in Business Intelligence (BI). Passionate about transforming HR data into actionable insights that support strategic decision-making and enhance organizational performance. Holding a master's degree in Economic and Organizational Sociology, which provides a unique perspective on the social and behavioral aspects of human resources. Based in Kecskemét, near Budapest, Hungary, and a proud parent of two boys. Loves to dance and is dedicated to continuous learning, always seeking new knowledge and skills to bring to the field.",

    "Ana Voicu": "Ana Voicu is a seasoned data engineer with a deep passion for databases, business intelligence, and data science. She specializes in developing enterprise-level Business Intelligence solutions across diverse industries, focusing on performance optimization, pattern recognition, efficient business process analysis, and interactive visualizations. Ana thrives on tackling database performance challenges, particularly those involving high data volume applications. Beyond her technical expertise, she has a strong enthusiasm for sharing her knowledge and insights with others, fostering a collaborative and continuous learning environment.",

    "Reitse Eskens": "Reitse began his computer days with GW Basic and quickly followed with Windows 3.11. After that, many computers followed, and, interrupted by human resource and psychology studies, he got into the IT work field around 2007. There, he encountered Oracle 9, which had a command line from 1980. At his current job, he met SQL Server. And loved it. Now he's working with SQL 2008 to SQL 2019 on-premises and several Azure SQL Databases, supporting customers and tuning databases. New projects focus more on the Azure data platform as an architect, security advisor and data engineer. They include Fabric (Lakehouse and Realtime solutions), Data Factory and Synapse Analytics.",

    "Estera Kot": "Dr. Estera Kot is the Chief Technology Officer at Clouds On Mars, where she drives the company's innovation in Data & AI strategy and execution. A former Principal Product Manager at Microsoft, she played a key role in building performance-critical components of Azure Synapse Analytics and Microsoft Fabric, focusing on Apache Spark and high-efficiency analytical engines. Estera is a Polish-born engineer by passion, fluent in several programming languages and recognized for her hands-on technical depth. She earned her Ph.D. in Computer Science with distinction, specializing in machine and deep learning for medical imaging. Her research has led to numerous scientific publications and a U.S. patent in big data processing. Her career spans global tech leaders like Intel, Sony, and Procter & Gamble. She is a respected educator and mentor, having designed full-time and postgraduate AI-in-Cloud programs at the Warsaw University of Technology. Her students now work at CERN, Google, Meta, and other top-tier institutions worldwide. Estera is a guest lecturer at UCLA—one of the top public research universities in the U.S.—and Łazarski University in Warsaw. As a speaker, she's presented at top industry events including MLADS (Microsoft's internal AI and data science conference in Redmond), the inaugural FabCon in Las Vegas, and several AI and cloud conferences across Europe. She also produces educational content on YouTube, making complex AI topics accessible and practical. Estera is committed to building scalable, ethical, and real-world-driven AI solutions, with a focus on impact over hype.",

    "Pragati Jain": "Pragati is a Data Platform MVP (Microsoft Most Valuable Professional). Currently, she is working as a Manager at Avanade in UK and works towards generating and delivering data insights to various customers. She holds a Master's degree in Data Science and Analytics from Royal Holloway University of London. She is skilled in various tools and technologies like Microsoft Fabric, Microsoft Power BI, Tableau, Microsoft Excel, Azure ML Studio, Azure Databricks Pyspark and SQL. She has been using Power BI for few years now and is recognized as a Superuser on the Microsoft Fabric Community. Outside work she enjoys photography, loves hiking, she is a trained Indian classical singer and has a passion for painting. She even has her Instagram page dedicated to painting.",

    "Tomaž Kaštrun": "Tomaž Kaštrun is a SQL Server developer and data scientist with more than 15 years of experience in the fields of business warehousing, development, ETL, database administration, and query tuning. He holds over 15 years of experience in data analysis, data mining, statistical research, and machine learning. He is a Microsoft SQL Server MVP for data platform and has been working with Microsoft SQL Server since version 2000. He is a blogger, author of many articles, a frequent speaker at the community and Microsoft events. He is an avid coffee drinker who is passionate about fixed gear bikes. In 2018 he co-authored book \"SQL Server 2017 Machine Learning Services with R\".",

    "Tillmann Eitelberg": "Tillmann Eitelberg is CEO and co-founder of oh22information services GmbH, which specializes in data management and data governance and offers its own cloud born data quality solution, HEDDA.IO. Tillmann is a regular speaker at international conferences and an active blogger and podcaster at DECOMPOSE.IO. He has open sourced several SSIS components and is Co-Author of Power BI for Dummies (German Edition). Since 2013 is Tillmann is awarded as Microsoft Data Platform MVP. He is a user group leader for the PASS Germany RG Rheinland (Cologne) and a member of the Microsoft Azure Data Community Advisory Board.",

    "Marjolein Opsteegh": "My name is Marjolein Opsteegh, I'm a Microsoft Data Platform MVP and a big Power BI enthusiast, living in the Netherlands, who loves to share knowledge, especially about the intersection of Power BI, UI, and UX. As a consultant, I design and build dashboards that are both visually appealing and user-friendly, keeping end-users in mind throughout the process. In addition to creating dashboards, I enjoy writing about frontend principles and sharing practical tips to help others get the most out of Power BI. I frequently speak at events and host Q & A sessions, inspiring others to improve their skills and embrace the power of data visualization, both off- and online.",

    "Cornelia Volaucnik": "Ich bin Data Scientist bei ACP Cubido Digital Solutions GmbH in Leonding. Mein Background von der Johannes Kepler Universität ist im Bereich Statistik und Artificial Intelligence. Bei ACP Cubido arbeite ich in der Umsetzung von verschiedenen Data Science und AI Projekten, von Datenaufbereitung und Prognosen bis hin zu GenAI und MLOps.",

    "Traci Sewell": "Traci joined the community to take the tech down a notch! She lives in Somerset with some (very cute) cats, some horses, some sheep, and her husband, Rob. When not looking after all of those, she also works to sooth people's minds as a psychotherapist. Being tech-adjacent she has been drawn into the tech event organising world and the wider community, where she brings her life long knowledge, expertise and fearsome determination to empower and protect those who are outside of the generic majority box. Over the past few years she has also found a voice as a speaker, sharing information and insights into all things mental health and wellbeing.",

    "Gabi Münster": "Gabi Münster (she / her) started working with SQL Server technologies in 2005. After some short excursions into Web Application development and a long and inspiring time as a BI consultant / Data architect at oh22data AG (including experiencing being a Data Platform MVP), she joined Microsoft as a Senior Program Manager at the Fabric CAT team in March 2022. She speaks at regional chapter meetings, national and international conferences. Since 2016 she also supports a regional chapter as co-lead. Apart from BI topics she also supports Diversity topics.",

    "Erwin de Kreuk": "Erwin de Kreuk is a passionate and highly experienced Technology Leader in the Data & AI domain. He currently serves as a Principal Consultant and Lead Data and AI at InSpark, winner of the Global Partner of the Year (POTY) Award for Identity and the Dutch Partner of the Year (POTY) Award for Data & AI. Erwin is a frequent speaker at various national and international data community events and has been recognized as a Data Platform MVP. With 16 years of experience in the world of data on the Microsoft Platform, Erwin has spent the last 8 years focusing on the Azure Platform. His day-to-day work involves addressing complex customer cases and technical issues. Additionally, he is a member of the Technology Board at InSpark, where he leads a team of highly experienced Data Experts specializing in the Microsoft Data Platform. Erwin is dedicated to helping customers maximize the value of their complex analytics environments, with a strong emphasis on solutions in the Azure Cloud (Platform as a Service) and Microsoft Fabric. As a Technology Board member, he continuously explores the latest opportunities and shares his enthusiasm with colleagues, the community, and customers. He is also a key stakeholder for the InSpark Solution (Managed) Oxygen, a Modern Data Platform Estate as-a-service and the Nitrogen Control Center a native solution build on top of Microsoft Fabric for easy data integration and data Processing.",

    "Karianne Kies": "Karianne is a Data Engineer with experience in implementing Fabric environments, as well as BI and data governance projects within the consulting industry. She is passionate about developing solutions that empower organizations to gain complete visibility and control over their data.",

    "Katharina Covadonga Clören": "Hi there, my name is Katharina Covadonga Clören. I discovered my passion for data analysis and reporting during my studies – quite unexpectedly, in a student job. That's when I realized how much I enjoy analyzing complex patterns and bringing them to life through creative visuals. For me, data visualization is the perfect blend of analytical detective and creative artist: I love uncovering hidden insights and presenting them in a way that's clear, engaging, and impactful. For the past two years, I've been working as a consultant with a focus on Data Analytics and Data Storytelling. What fascinates me most is the incredible potential and variety that lies in good visualizations. Before starting my consulting career, I spent a year traveling around the world – driven by curiosity, a love for adventure, and an open mind for people, cultures, and new perspectives. That same openness shapes the way I work today: Data is everywhere, and it always tells a story – you just have to listen (and look) closely. When I'm not building reports or analyzing data, you'll find me doing yoga, bouldering, enjoying food from around the world, or exploring the planet.",

    "Gianluca Sartori": "Gianluca Sartori is a Data Platform MVP, independent consultant and performance tuning specialist. He has been working in the software industry since 1999 and has been working with SQL Server ever since. He also works as a SQL Server trainer and in his spare time he writes technical articles and participates the SQL Server forums. Gianluca enjoys presenting SQL Server topics at conferences in Europe and US. He is currently working as lead DBA at a famous Formula 1 team.",

    "Florian Stein": "My name is Florian Stein, and I am an expert in Industrial IoT, Manufacturing, and Cloud/Edge infrastructures. I have contributed to significant projects, including the publication \"Factory Innovation: Successfully Navigating Digital Transformation through the IoT Adoption Framework\" and a presentation on \"Manufacturing Traceability at Scale\" at Hannover Messe 2024. I have also discussed IoT in waste management on the \"IoT Use Case Podcast.\" In my spare time, I love playing tennis, surfing, and perfecting my coffee-making techniques as a barista.",

    "Vivek Trivedi": "Vivek Trivedi is a Cloud Security Solutions Architect with over 20 years of experience in cloud, data, and security solutions. He is the founder of CloudArc Consultants LLC (UAE) and Arnav Tech Solutions (India), specializing in Microsoft Azure, Microsoft Fabric ,Power BI, Purview, and the Power Platform. Vivek has delivered governance and analytics projects for leading organizations including EY, Microsoft ESI, Airbus Defense, HSBC, and Red Sea Global. A Microsoft Certified Azure Solutions Architect Expert with multiple Power BI and security certifications, he is a trusted speaker who bridges technical and business needs, helping enterprises enable secure and governed analytics.",

    "Damir Matešić": "For many years Damir is a passionate programmer and a Microsoft SQL Server developer (ver. 2000+). He is a certificated Microsoft professional on various technologies. He leads the Croatian SQL Server User Group and he introduced SQL Saturday Event in Croatia. He organizes various Data Platform events in Croatia. Founder and organizer of #DataWeekender. #DataWeekender is a popup online conference, organized by a group of European based Microsoft data platform professionals. Originally created as a response to Covid-19, this is now a regular online event. He is currently working as Senior Database Architect @Span.eu. Damir speaks on various community events, conferences and user groups. When free he blogs about SQL @ https://blog.matesic.info.",

    "Filip Popović": "Filip Popović is a Senior Product Manager at Microsoft and part of the Fabric Product Group, focusing on SQL performance. Before joining Microsoft in 2019, he spent over ten years in the software and financial services industry, delivering business analytics solutions using the Microsoft technology stack.",

    "Daniel Patkos": "I began my career as a business and technology consultant, quickly transitioning into implementation and BI development. I have extensive experience with various data analysis and BI tools, including Tableau, Spotfire, Domo, and Power BI. Since 2018, my primary focus has been on deepening my knowledge of the Power BI ecosystem. While I am passionate about data visualization, I also have a strong affinity for data transformation and data modeling. I thoroughly enjoy solving ETL challenges using Power BI Dataflow and Power Query.",

    "Theresa Hirz": "Ich bin Data Scientistin bei der ACP CUBIDO Digital Solutions GmbH in Leonding. Meinen Master habe ich an der FH Oberösterreich in Hagenberg im Bereich Data Science and Engineering absolviert und mich dabei vor allem auf den Bereich Computer Vision spezialisiert.",

    "Grant Fritchey": "Grant Fritchey is a Data Platform MVP and AWS Community Builder with over 30 years' experience in IT, including time spent in support and development. Grant works with multiple data platforms including SQL Server and PostgreSQL as well as multiple cloud platforms. He has also developed in VB, VB.NET, C#, and Java. Grant writes books for Apress and Simple-Talk. Grant presents at conferences and user groups, large and small, all over the world. He joined Redgate Software as a product advocate in January 2011.",

    "Anastasia Salari": "On a mission to turn everyday users into data heroes through Microsoft Technology.",

    "Vitalija Bartusevičiūtė": "Vitalija thrives on turning complex data into actionable insights. For her PhD she spent years in a lab collecting data on fish, and gained a deep understanding on science-grade quantitative analytics. Today she work as a business analytics consultant using Microsoft technology, primarily Azure Databricks. She loves to talk about data and exchange best practices. When not at work you can her working on her next ceramics project.",

    "Ben Weissman (he/him)": "Ben has been working with SQL Server since SQL Server 6.5, mainly in the BI/Datawarehousing field. He is a Microsoft Data Platform MVP, a co-author of \"SQL on Kubernetes\", \"Azure Arc-enabled Data Services Revealed\", \"SQL Server Big Data Clusters\" and \"The Biml Book\" as well as a regular speaker at national and international events. He has also published multiple Video courses at Pluralsight and other platforms. Ben is also a co-organizer of DataGrillen, New Stars of Data and dativerse as well as a volunteer and mentor for many other Data Platform events.",

    "Jasmin Simader": "BI Consultant with a passion for Data Health - helping organizations move from messy data to reliable decisions.",

    "Benni De Jagere": "Benni is a Principal Program Manager in the Fabric Customer Advisory Team (Fabric CAT) at Microsoft. Aspiring to be top notch in his field, through continuous personal development, on both technical and soft skills. He strives for maximum results in his tasks using team play, communication, thinking outside of the box, and (endless) motivation. Benni is always ready to tackle the unknown, or pick up fresh ideas to broaden his range. Building on past experiences, he continuously tries to find new, more efficient ways of obtaining results, and improving the process along the way. Loving (almost) every day of it, he's fascinated by the value of data, sometimes flabbergasted by the lack of awareness, and intrigued by the endless possibilities whilst discovering new ways of looking at data. He thrives on unfolding new insights for customers whilst using an open and transparent communication. On a daily basis he turns (large amounts of) coffee into insights for customers, and references witty British comedy, lame dad jokes, and obscure facts way too often. Overly enthusiastic about anything data related, he's trying hard to keep up with all things new and shiny. When not working, blogging or reading, you'll likely find him out and about being his weird self. Rumour has it that he's also involved with a ragtag band of data enthusiasts, enjoying themselves whilst organising cool community things. They go by the name of .. dataMinds!",

    "Alexander Klein": "Alexander Klein is a senior Business Intelligence consultant with more than 20 years of experience. He focuses on Business Intelligence and Data Warehouse projects with Microsoft technologies like SQL Server, Power BI, Azure ML or Cognitive Services. Since 2008, he has been a self-employed consultant in large and medium-sized projects in all sectors across Europe. He has been visiting SQL Saturdays all over Europe since 2013.Since 2017 Alexander speaks at national and international conferences / user groups about Data Warehouse, BI, Azure and AI.",

    "Christian Henrik Reich": "Sr Solution Architect @ Microsoft. Started programming as kid, and still do. Have made everything from embedded programming to data warehouses. Last decade, focus has mainly been on data. From optimizing and infrastructure to designing and building data solutions in cloud and on-premise.",

    "Erland Sommarskog": "Erland Sommarskog is an independent consultant based in Stockholm. He has worked with SQL Server since 1991. He was first awarded SQL Server MVP in 2001, and he has been re-awarded every year since. His focus is on systems development with the SQL Server Database Engine and his passion is to help people to write better SQL Server applications.",

    "Ynte Jan Kuindersma": "Ynte Jan Kuindersma is a Senior Technology Advisor and Developer at BIRD Automation. He is a longtime freelance developer of database-driven applications in the Microsoft Universe. Since 2015 he uses Power BI and the surrounding Power Platfom tools. His goal is not just programming, but making people and organizations more efficient in their daily work by means of some clever code and ETL. And he is very persistent in finding the best way to find a solution for a given problem. Besides programming he is an enthusiastic teacher and speaker at community developer conferences. Dived into Fabric from the beginning and earned a DP 600 Microsoft Certified: Fabric Analytics Engineer Associate certificate in Juni 2024."
}

# Load conference.json
print("Loading conference.json...")
with open('data/conference.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

# Update bios
updated = 0
for speaker in data['speakers']:
    name = speaker['name']
    if name in speaker_bios:
        speaker['bio'] = speaker_bios[name]
        updated += 1
        try:
            print(f"[OK] Updated: {name}")
        except:
            print(f"[OK] Updated speaker (name contains special chars)")

print(f"\n{updated} speaker bios updated out of {len(data['speakers'])} total speakers")

# Save updated data
print("\nSaving updated conference.json...")
with open('data/conference.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, indent=2, ensure_ascii=False)

print("[DONE] Now run: python generate_faq.py")
